export type SubSkill = { skill: string; accuracy: number; time: string; status: string };
export type ActionPlanItem = { title: string; steps: string[] };
export type Domain = {
  name: string; shortName: string; score: number; max: number; percentage: number;
  correct: number; total: number; time: string; ratio: number;
  color: string; fill: string; border: string; bgTint: string; text: string;
  date: string; description: string; label: string; insights: string;
  strengths: string[]; improvements: string[];
  actionPlan: { high: ActionPlanItem; medium: ActionPlanItem; low: ActionPlanItem };
  subSkills: SubSkill[];
};
export type Overall = {
  score: number; maxScore: number; percentage: number; band: string;
  totalQuestions: number; correctAnswers: number; accuracy: number;
  timeTaken: string; timeEfficiency: string; needsAttention: number; estTotalTime: string;
};
export type Psychometric = { trait: string; score: number; percentile: number; status: string };
export type StudentReport = { overall: Overall; domains: Domain[]; psychometric: Psychometric[]; summary: string };

type DomainStyle = { color: string; fill: string; border: string; bgTint: string; text: string };

const d = (
  name: string, shortName: string, score: number, max: number, percentage: number,
  correct: number, total: number, time: string, ratio: number,
  style: DomainStyle,
  date: string, description: string, label: string, insights: string,
  strengths: string[], improvements: string[],
  high: ActionPlanItem, medium: ActionPlanItem, low: ActionPlanItem,
  subSkills: SubSkill[]
): Domain => ({
  name, shortName, score, max, percentage, correct, total, time, ratio,
  ...style,
  date, description, label, insights,
  strengths, improvements, actionPlan: { high, medium, low }, subSkills,
});

const COG: DomainStyle = { color:'bg-rose-500',   fill:'#f43f5e', border:'border-rose-500',   bgTint:'bg-rose-50/50',   text:'text-rose-700'   };
const BIZ: DomainStyle = { color:'bg-blue-500',   fill:'#3b82f6', border:'border-blue-500',   bgTint:'bg-blue-50/50',   text:'text-blue-700'   };
const PRB: DomainStyle = { color:'bg-purple-500', fill:'#a855f7', border:'border-purple-500', bgTint:'bg-purple-50/50', text:'text-purple-700' };
const COM: DomainStyle = { color:'bg-orange-500', fill:'#f97316', border:'border-orange-500', bgTint:'bg-orange-50/50', text:'text-orange-700' };
const LDR: DomainStyle = { color:'bg-emerald-500',fill:'#10b981', border:'border-emerald-500',bgTint:'bg-emerald-50/50',text:'text-emerald-700'};
const DIG: DomainStyle = { color:'bg-teal-500',   fill:'#14b8a6', border:'border-teal-500',   bgTint:'bg-teal-50/50',   text:'text-teal-700'   };

const STUDENT_DATA: Record<string, StudentReport> = {
  // ── STU001 Allen · MBA · GREEN ──────────────────────────────────────────
  STU001: {
    overall: { score:77.2, maxScore:100, percentage:77.2, band:'EXCEPTIONAL', totalQuestions:127, correctAnswers:98, accuracy:77.2, timeTaken:'300m 34s', timeEfficiency:'0.95x avg', needsAttention:29, estTotalTime:'310m 00s' },
    domains: [
      d('Cognitive Intelligence','Cognitive',18,21,85.7,18,21,'47m 15s',0.95,COG,'20 Mar 2026, 09:00 AM','Assesses logical reasoning, analytical thinking, and problem-solving speed.','STRONG',
        'Allen shows exceptional logical reasoning and pattern recognition. He processes complex information quickly and maintains high accuracy.',
        ['High analytical speed','Strong logical deduction','Pattern recognition'],
        ['Complex verbal syllogisms','Sustained attention on long passages'],
        {title:'Advanced Logic',steps:['Practice complex multi-step logical puzzles.','Review advanced deduction frameworks.']},
        {title:'Sustained Attention',steps:['Practice longer reading sets (20+ minutes).','Use focus-building techniques during mock tests.']},
        {title:'Maintain Edge',steps:['Continue semi-weekly cognitive drills to keep speed high.']},
        [{skill:'Logical Reasoning',accuracy:90,time:'Fast (0.8x)',status:'Exceptional'},{skill:'Quantitative Aptitude',accuracy:82,time:'Avg (1.0x)',status:'Strong'}]),
      d('Business Intelligence','Business',16,20,80.0,16,20,'46m 40s',0.98,BIZ,'20 Mar 2026, 10:15 AM','Evaluates understanding of business concepts, market dynamics, and strategic thinking.','STRONG',
        'Strong grasp of business fundamentals and market mechanics. Can identify primary value drivers in business scenarios.',
        ['Market sizing acumen','Financial metric awareness','Strategic framework application'],
        ['Cross-functional impact analysis','Macro-economic trend spotting'],
        {title:'Strategy Expansion',steps:['Analyze how supply chain shifts impact firm value.','Review integrated business case studies.']},
        {title:'Market Trends',steps:['Follow regional market reports daily.','Practice predicting market response to fiscal policy changes.']},
        {title:'Financial Depth',steps:['Review deeper capital budgeting concepts.']},
        [{skill:'Market Analysis',accuracy:85,time:'Avg (0.9x)',status:'Strong'},{skill:'Financial Acumen',accuracy:75,time:'Avg (1.0x)',status:'Strong'}]),
      d('Problem Solving','Problem Solving',15,19,78.9,15,19,'45m 55s',1.01,PRB,'20 Mar 2026, 11:30 AM','Measures ability to identify issues, analyze root causes, and develop effective solutions.','STRONG',
        'Systematic approach to breaking down problems. Generally accurate, though could improve on creative solution generation.',
        ['Root cause identification','Logical problem decomposition','Framework application'],
        ['Lateral thinking','Creative brainstorming','Multi-variable optimization'],
        {title:'Creative Thinking',steps:['Practice lateral thinking exercises.','Brainstorm 3 diverse solutions for every mock case.']},
        {title:'Complex Systems',steps:['Study system dynamics and feedback loops.','Practice mapping out complex interdependencies.']},
        {title:'RCA Polish',steps:['Review advanced 5-Why techniques for deeper root causes.']},
        [{skill:'Data Interpretation',accuracy:80,time:'Avg (1.0x)',status:'Strong'},{skill:'Solution Generation',accuracy:77,time:'Avg (1.1x)',status:'Strong'}]),
      d('Communication','Communication',11,14,78.6,11,14,'35m 0s',1.07,COM,'20 Mar 2026, 01:00 PM','Tests verbal and written communication skills, clarity, and articulation.','STRONG',
        'Allen is clear and professional in his communication. Good articulating technical ideas, but slightly slower on nuanced prompts.',
        ['Clarity of message','Professional tone','Structured emails'],
        ['Nuance detection','Adaptive storytelling','Public speaking confidence'],
        {title:'Professional Nuance',steps:['Draft responses to complex, emotionally-charged scenarios.','Analyze tone in high-stakes corporate communication.']},
        {title:'Public Speaking',steps:['Record and review short presentations.','Focus on pacing and filler word reduction.']},
        {title:'Active Listening',steps:['Summarize long, unstructured group discussions.']},
        [{skill:'Written Ability',accuracy:82,time:'Avg (1.0x)',status:'Strong'},{skill:'Verbal Fluency',accuracy:75,time:'Slow (1.2x)',status:'Average'}]),
      d('Leadership','Leadership',14,16,87.5,14,16,'36m 48s',0.97,LDR,'20 Mar 2026, 02:45 PM','Assesses team management, decision-making, and ability to inspire others.','EXCEPTIONAL',
        'Excellent natural leadership. Allen makes sound decisions and understands how to motivate team members effectively.',
        ['Decisive leadership','Team motivation','Conflict resolution'],
        ['Strategic delegation','Vision alignment'],
        {title:'Vision Casting',steps:['Practice articulating 5-year visions for small projects.','Map short-term tasks to long-term strategic goals.']},
        {title:'Delegation Mastery',steps:['Framework for task-based vs goal-based delegation.','Study coaching techniques for team development.']},
        {title:'Crisis Management',steps:['Stress-test decision making in time-pressured scenarios.']},
        [{skill:'Decision Making',accuracy:90,time:'Fast (0.9x)',status:'Exceptional'},{skill:'Team Empathy',accuracy:85,time:'Avg (1.0x)',status:'Strong'}]),
      d('Digital Business','Digital Business',24,37,64.9,24,37,'88m 48s',0.97,DIG,'20 Mar 2026, 04:00 PM','Evaluates knowledge of digital trends, e-commerce, and technology integration in business.','AVERAGE',
        'Fair understanding of digital trends, but requires more depth in technical integration and data privacy areas.',
        ['Basic digital marketing awareness','E-commerce model understanding'],
        ['Data privacy laws (GDPR/CCPA)','Enterprise software architecture','Emerging tech stacks'],
        {title:'Privacy & Compliance',steps:['Complete short modules on data protection basics.','Study case studies of data breach impacts on brands.']},
        {title:'Tech Integration',steps:['Understand API-first business models.','Review cloud migration strategy fundamentals.']},
        {title:'Digital Strategy',steps:['Practice building digital-first product roadmaps.']},
        [{skill:'Digital Trends',accuracy:68,time:'Avg (1.0x)',status:'Average'},{skill:'Tech Literacy',accuracy:62,time:'Avg (1.1x)',status:'Average'}]),
    ],
    psychometric:[{trait:'Openness',score:82,percentile:88,status:'PASS'},{trait:'Conscientiousness',score:90,percentile:94,status:'PASS'},{trait:'Extraversion',score:70,percentile:75,status:'PASS'},{trait:'Agreeableness',score:85,percentile:88,status:'PASS'},{trait:'Neuroticism (Low)',score:78,percentile:80,status:'PASS'}],
    summary: 'Allen demonstrated a strong overall performance with an accuracy of 77.2%, placing him in the GREEN band. His strongest domain is Leadership (87.5% accuracy), showcasing excellent decision-making skills. His weakest domain is Digital Business (64.9% accuracy). Time efficiency is solid at an average of 142s per question. To improve, Allen should focus on Numerical Reasoning, as he missed some easy questions in this area, which requires attention to detail under time constraints.',
  },

  // ── STU002 Swetha · MBA · AMBER ──────────────────────────────────────────
  STU002: {
    overall: { score:59.1, maxScore:100, percentage:59.1, band:'GOOD', totalQuestions:127, correctAnswers:75, accuracy:59.1, timeTaken:'328m 15s', timeEfficiency:'1.09x avg', needsAttention:52, estTotalTime:'340m 00s' },
    domains: [
      d('Cognitive Intelligence','Cognitive',14,21,66.7,14,21,'52m 30s',1.06,COG,'20 Mar 2026, 09:00 AM','Assesses logical reasoning, analytical thinking, and problem-solving speed.','AVERAGE',
        'Consistent cognitive processing, but struggles with accuracy under timed pressure on complex sets.',
        ['Steady processing pace','Basic logical patterns'],
        ['Speed-accuracy trade-off','Complex numerical sets'],
        {title:'Speed Drills',steps:['Practice timed mental math daily.','Set strict 1-minute limits for logic puzzles.']},
        {title:'Numerical Accuracy',steps:['Review core arithmetic and percentage calculation shortcuts.','Practice data interpretation sets multiple times.']},
        {title:'Focus Training',steps:['Meditation techniques for improved concentration during tests.']},
        [{skill:'Logical Reasoning',accuracy:68,time:'Avg (1.1x)',status:'Average'},{skill:'Quantitative Aptitude',accuracy:65,time:'Slow (1.2x)',status:'Average'}]),
      d('Business Intelligence','Business',12,20,60.0,12,20,'53m 20s',1.13,BIZ,'20 Mar 2026, 10:15 AM','Evaluates understanding of business concepts, market dynamics, and strategic thinking.','AVERAGE',
        'Fundamental understanding of marketing and consumer behavior, but limited exposure to corporate strategy and finance.',
        ['Consumer insights','Basic marketing mix understanding'],
        ['Corporate finance basics','Strategic analysis tools (BCG Matrix, etc)'],
        {title:'Finance 101',steps:['Complete module on reading basic financial statements.','Practice ROI calculations for marketing campaigns.']},
        {title:'Strategy Tools',steps:['Study application of Porter\'s 5 Forces to 3 industries.','Review case studies on competitive advantage.']},
        {title:'Economic Awareness',steps:['Read the financial section of a major newspaper daily.']},
        [{skill:'Market Awareness',accuracy:62,time:'Slow (1.2x)',status:'Average'},{skill:'Business Strategy',accuracy:58,time:'Slow (1.1x)',status:'Average'}]),
      d('Problem Solving','Problem Solving',11,19,57.9,11,19,'50m 10s',1.11,PRB,'20 Mar 2026, 11:30 AM','Measures ability to identify issues, analyze root causes, and develop effective solutions.','AVERAGE',
        'Can identify primary issues, but solution path often lacks depth or multi-variable consideration.',
        ['Issue identification','Structured brainstorming'],
        ['Root cause depth','Solution evaluation metrics'],
        {title:'Deeper Root Causes',steps:['Practice 5-Whys on operational failures.','Use fishbone diagrams to map out complex problems.']},
        {title:'Metric-Based Solutions',steps:['Define success metrics before proposing any solution.','Practice cost-benefit analysis of suggested fixes.']},
        {title:'System Thinking',steps:['Study basic system dynamics and loop diagrams.']},
        [{skill:'Data Analysis',accuracy:59,time:'Slow (1.1x)',status:'Average'},{skill:'Solution Ideation',accuracy:56,time:'Slow (1.2x)',status:'Average'}]),
      d('Communication','Communication',8,14,57.1,8,14,'38m 30s',1.16,COM,'20 Mar 2026, 01:00 PM','Tests verbal and written communication skills, clarity, and articulation.','AVERAGE',
        'Standard business communication is okay, but professional technical writing and persuasive skills need focus.',
        ['General clarity','Professional etiquette'],
        ['Professional writing precision','Data storytelling','Persuasive speaking'],
        {title:'Professional Writing',steps:['Focus on Professional Writing & Email precision.','Practice executive summary drafting.']},
        {title:'Data Storytelling',steps:['Use charts to build a narrative.','Practice translating dataset into 3 key bullet points for execs.']},
        {title:'Persuasion Basics',steps:['Study frameworks for influence and persuasion in business.']},
        [{skill:'Written Precision',accuracy:58,time:'Slow (1.2x)',status:'Average'},{skill:'Verbal Impact',accuracy:56,time:'Slow (1.1x)',status:'Average'}]),
      d('Leadership','Leadership',10,16,62.5,10,16,'40m 32s',1.07,LDR,'20 Mar 2026, 02:45 PM','Assesses team management, decision-making, and ability to inspire others.','AVERAGE',
        'Comfortable in team environments, but needs more confidence in taking decisive action and conflict management.',
        ['Team participation','Empathy'],
        ['Decisive action','Conflict mediation','Goal setting'],
        {title:'Decisive Management',steps:['Framework for making decisions with 70% information.','Study high-stakes leadership biographies.']},
        {title:'Conflict Resolution',steps:['Practice difficult conversations through role-play.','Study interest-based negotiation techniques.']},
        {title:'Goal Definition',steps:['Practice setting SMART goals for small teams.']},
        [{skill:'Decision Confidence',accuracy:64,time:'Avg (1.1x)',status:'Average'},{skill:'Team Coordination',accuracy:61,time:'Slow (1.1x)',status:'Average'}]),
      d('Digital Business','Digital Business',20,37,54.1,20,37,'95m 10s',1.08,DIG,'20 Mar 2026, 04:00 PM','Evaluates knowledge of digital trends, e-commerce, and technology integration in business.','AVERAGE',
        'Basic digital literacy, but lacks depth in e-commerce strategy and technological frameworks.',
        ['Social media awareness','Digital platform familiarity'],
        ['E-commerce logistics & strategy','Data literacy & analytics','Tech ecosystem maps'],
        {title:'Digital Fundamentals',steps:['Complete Google Digital Garage or similar foundation course.','Analyze e-commerce value chains for 2 different brands.']},
        {title:'Data Literacy',steps:['Focus on Storytelling with Data foundations.','Practice basic data visualization in Excel/Tableau.']},
        {title:'Tech Awareness',steps:['Map out the tech stack of a common consumer app.']},
        [{skill:'Digital Trends',accuracy:55,time:'Slow (1.1x)',status:'Average'},{skill:'Market Tech',accuracy:53,time:'Slow (1.2x)',status:'Average'}]),
    ],
    psychometric:[{trait:'Openness',score:70,percentile:72,status:'PASS'},{trait:'Conscientiousness',score:75,percentile:78,status:'PASS'},{trait:'Extraversion',score:65,percentile:66,status:'PASS'},{trait:'Agreeableness',score:80,percentile:82,status:'PASS'},{trait:'Neuroticism (Low)',score:60,percentile:62,status:'PASS'}],
    summary: 'Swetha achieved an overall accuracy of 59.1%, placing her in the AMBER band. Her strongest domain is Cognitive Intelligence (66.7% accuracy), while her weakest is Digital Business (54.1% accuracy). Her average time taken is slightly high at 155s per question. Improvement is urgently needed in Communication and Digital Business, specifically focusing on Professional Writing & Email, Persuasion & Influence, Storytelling with Data, and Data Literacy, as she missed several easy questions in these fundamental areas.',
  },

  // ── STU003 Aishwarya · MBA · AMBER ───────────────────────────────────────
  STU003: {
    overall: { score:68.5, maxScore:100, percentage:68.5, band:'GOOD', totalQuestions:127, correctAnswers:87, accuracy:68.5, timeTaken:'292m 6s', timeEfficiency:'0.97x avg', needsAttention:40, estTotalTime:'300m 00s' },
    domains: [
      d('Cognitive Intelligence','Cognitive',16,21,76.2,16,21,'47m 15s',0.95,COG,'20 Mar 2026, 09:00 AM','Assesses logical reasoning, analytical thinking, and problem-solving speed.','STRONG',
        'Strong cognitive foundations with good performance in numerical and logical deduction. Efficient time manager.',
        ['Logical deduction','Numerical fluency','Time management'],
        ['Abstract spatial complexity','Speed on multi-layer problems'],
        {title:'Spatial Mastery',steps:['Practice abstract pattern recognition daily.','Review 3D object rotation puzzles.']},
        {title:'Multi-Layer Logic',steps:['Practice problems requiring 3+ logical steps.','Break down large problems into logical chains.']},
        {title:'Maintain Momentum',steps:['Continue semi-weekly drills to maintain current rapid pace.']},
        [{skill:'Logical Reasoning',accuracy:78,time:'Fast (0.9x)',status:'Strong'},{skill:'Quantitative Aptitude',accuracy:74,time:'Avg (1.0x)',status:'Strong'}]),
      d('Business Intelligence','Business',14,20,70.0,14,20,'46m 40s',1.00,BIZ,'20 Mar 2026, 10:15 AM','Evaluates understanding of business concepts, market dynamics, and strategic thinking.','STRONG',
        'Good grasp of market dynamics and business scenarios. Solid understanding of KPI management.',
        ['Market trend analysis','KPI definition','Business model awareness'],
        ['Unit Economics depth','Revenue model complexities'],
        {title:'Economics Depth',steps:['Focus on Unit Economics & Revenue Models.','Practice calculating CAC, LTV and Gross Margins.']},
        {title:'Case Application',steps:['Review 5 strategy case studies on revenue model pivots.','Analyze business model shifts of major tech firms.']},
        {title:'Industry Research',steps:['Specific deep dive into finance and retail business models.']},
        [{skill:'Strategic Thinking',accuracy:72,time:'Avg (1.0x)',status:'Strong'},{skill:'Financial Metrics',accuracy:68,time:'Avg (1.1x)',status:'Strong'}]),
      d('Problem Solving','Problem Solving',13,19,68.4,13,19,'45m 0s',1.04,PRB,'20 Mar 2026, 11:30 AM','Measures ability to identify issues, analyze root causes, and develop effective solutions.','AVERAGE',
        'Aishwarya is a steady problem solver but sometimes misses deeper root causes or cost dependencies.',
        ['Structured analysis','Steady approach','Alternative ideation'],
        ['Root cause depth','Cost-benefit modeling'],
        {title:'Deeper Analysis',steps:['Apply MECE framework to problem decomposition.','Practice 5-Whys on complex organizational scenarios.']},
        {title:'Efficiency Modeling',steps:['Practice modeling cost of various solution paths.','Optimize solutions for multiple constraints (time, budget, risk).']},
        {title:'Case Variety',steps:['Solve problems across diverse industries to broaden toolkit.']},
        [{skill:'Data Interpretation',accuracy:70,time:'Avg (1.0x)',status:'Strong'},{skill:'Logical Solutions',accuracy:67,time:'Slow (1.1x)',status:'Average'}]),
      d('Communication','Communication',10,14,71.4,10,14,'31m 44s',0.97,COM,'20 Mar 2026, 01:00 PM','Tests verbal and written communication skills, clarity, and articulation.','STRONG',
        'Effective communicator. Expresses ideas clearly and has a good professional vocabulary.',
        ['Clear articulation','Professional tone','Vocabulary usage'],
        ['Persuasive depth','Complex audience calibration'],
        {title:'Persuasive Impact',steps:['Study rhetorical devices in business speaking.','Practice drafting executive influence memos.']},
        {title:'Audience Nuance',steps:['Practice adapting the same message for technically diverse audiences.','Review cross-cultural communication best practices.']},
        {title:'Presentation Polish',steps:['Focus on visual delivery and non-verbal cues.']},
        [{skill:'Written Clarity',accuracy:75,time:'Avg (1.0x)',status:'Strong'},{skill:'Verbal Confidence',accuracy:68,time:'Fast (0.9x)',status:'Strong'}]),
      d('Leadership','Leadership',12,16,75.0,12,16,'37m 4s',1.00,LDR,'20 Mar 2026, 02:45 PM','Assesses team management, decision-making, and ability to inspire others.','STRONG',
        'Strong leadership potential. Motivates others well and manages peer dynamics effectively.',
        ['Team motivation','Peer mediation','Goal tracking'],
        ['Visionary communication','Managing senior stakeholders'],
        {title:'Strategic Leadership',steps:['Practice communicating long-term roadmaps to peers.','Learn how to manage up and handle senior stakeholder expectations.']},
        {title:'Coaching Skills',steps:['Study feedback models for peer development.','Practice delivering constructive feedback gracefully.']},
        {title:'Agile Leadership',steps:['Review agile team leadership principles and implementation.']},
        [{skill:'Team Management',accuracy:78,time:'Avg (1.0x)',status:'Strong'},{skill:'Decision Making',accuracy:72,time:'Avg (1.1x)',status:'Strong'}]),
      d('Digital Business','Digital Business',22,37,59.5,22,37,'84m 32s',0.97,DIG,'20 Mar 2026, 04:00 PM','Evaluates knowledge of digital trends, e-commerce, and technology integration in business.','AVERAGE',
        'Developing digital literacy. Good on trends, needs work on the operational back-end of digital firms.',
        ['E-commerce trend awareness','Digital advertising basics'],
        ['Digital supply chain','Data privacy regulations','Tech integrations'],
        {title:'Digital Back-end',steps:['Study the API economy and how apps talk to each other.','Review cloud infrastructure models (IaaS, PaaS, SaaS).']},
        {title:'Privacy Knowledge',steps:['Review fundamentals of GDPR and CCPA.','Study data compliance for global consumer brands.']},
        {title:'Growth Strategy',steps:['Analyze digital growth stacks of top SaaS firms.']},
        [{skill:'Digital Literacy',accuracy:62,time:'Avg (1.0x)',status:'Average'},{skill:'Trend Adoption',accuracy:57,time:'Fast (0.9x)',status:'Average'}]),
    ],
    psychometric:[{trait:'Openness',score:78,percentile:81,status:'PASS'},{trait:'Conscientiousness',score:82,percentile:85,status:'PASS'},{trait:'Extraversion',score:72,percentile:74,status:'PASS'},{trait:'Agreeableness',score:88,percentile:90,status:'PASS'},{trait:'Neuroticism (Low)',score:75,percentile:77,status:'PASS'}],
    summary: 'Aishwarya performed steadily with an overall accuracy of 68.5% (AMBER band) and a good time efficiency of 138s per question. Her strongest domain is Cognitive Intelligence (76.2% accuracy), while Digital Business is her weakest (59.5% accuracy). To elevate her performance to the GREEN band, she should focus on strengthening her understanding of Unit Economics & Revenue Models, where she missed foundational questions.',
  },

  // ── STU004 Thiganth · MBA · RED ──────────────────────────────────────────
  STU004: {
    overall: { score:49.6, maxScore:100, percentage:49.6, band:'DEVELOPING', totalQuestions:127, correctAnswers:63, accuracy:49.6, timeTaken:'338m 40s', timeEfficiency:'1.26x avg', needsAttention:64, estTotalTime:'360m 00s' },
    domains: [
      d('Cognitive Intelligence','Cognitive',11,21,52.4,11,21,'54m 15s',1.10,COG,'20 Mar 2026, 09:00 AM','Assesses logical reasoning, analytical thinking, and problem-solving speed.','AVERAGE',
        'Thiganth struggles with pattern recognition and complex logic, often taking more time for simple deductions.',
        ['Basic patterns','Steady effort'],
        ['Logical deduction speed','Numerical accuracy','Pattern Recognition'],
        {title:'Pattern Training',steps:['Focus on fundamental Pattern Recognition exercises.','Daily logic puzzles that emphasize sequence building.']},
        {title:'Accuracy Focus',steps:['Practice untimed sets first to ensure 100% understanding.','Gradually introduce 2-minute limits per question.']},
        {title:'Basic Arithmetic',steps:['Review numerical foundations for quicker estimations.']},
        [{skill:'Pattern Recognition',accuracy:54,time:'Slow (1.2x)',status:'Needs Work'},{skill:'Quantitative Ability',accuracy:51,time:'Slow (1.1x)',status:'Needs Work'}]),
      d('Business Intelligence','Business',10,20,50.0,10,20,'55m 0s',1.17,BIZ,'20 Mar 2026, 10:15 AM','Evaluates understanding of business concepts, market dynamics, and strategic thinking.','AVERAGE',
        'Limited awareness of business models and market operations. Needs significant immersion in business foundational concepts.',
        ['Consumer awareness','Basic terminology'],
        ['Business models','Competitive Analysis','Industry frameworks'],
        {title:'Model Literacy',steps:['Focus on Competitive Analysis & Business Models.','Study the top 20 business models used today.']},
        {title:'Framework Practice',steps:['Apply SWOT and PESTEL to local businesses.','Practice identifying competitive advantages in case fragments.']},
        {title:'Business News',steps:['Read the front page of a business daily every morning.']},
        [{skill:'Business Acumen',accuracy:52,time:'Slow (1.2x)',status:'Needs Work'},{skill:'Strategic Awareness',accuracy:48,time:'Slow (1.2x)',status:'Needs Work'}]),
      d('Problem Solving','Problem Solving',9,19,47.4,9,19,'51m 18s',1.14,PRB,'20 Mar 2026, 11:30 AM','Measures ability to identify issues, analyze root causes, and develop effective solutions.','WEAK',
        'Needs to revisit the basics of how to break down a problem and follow a logical path to a solution.',
        ['Identify simple issues','Willingness to try'],
        ['Problem decomposition','Root cause analysis','Logical sequencing'],
        {title:'Breaking it Down',steps:['Learn to decompose a big problem into 3 small ones.','Practice making simple flowcharts for daily tasks.']},
        {title:'Logical Paths',steps:['Review inductive vs deductive reasoning basics.','Solve simple multi-step word problems daily.']},
        {title:'Basic RCA',steps:['Apply 3-Whys to simple failure scenarios.']},
        [{skill:'Logical Paths',accuracy:48,time:'Slow (1.2x)',status:'Needs Work'},{skill:'Issue Discovery',accuracy:46,time:'Slow (1.1x)',status:'Needs Work'}]),
      d('Communication','Communication',7,14,50.0,7,14,'36m 52s',1.13,COM,'20 Mar 2026, 01:00 PM','Tests verbal and written communication skills, clarity, and articulation.','AVERAGE',
        'Communication style is often too brief or lacks professional structure. Clarity needs improvement.',
        ['Short answers','Basic politeness'],
        ['Professional depth','Clarity & structure','Storytelling'],
        {title:'Clear Structure',steps:['Use the SCR (Situation, Complication, Resolution) framework for updates.','Practice drafting 3-paragraph professional emails.']},
        {title:'Storytelling 101',steps:['Focus on Storytelling with Data basics.','Practice describing a concept in under 2 minutes.']},
        {title:'Verbal Prep',steps:['Read out loud to improve fluency and pacing.']},
        [{skill:'Message Clarity',accuracy:52,time:'Slow (1.1x)',status:'Needs Work'},{skill:'Professionalism',accuracy:48,time:'Slow (1.2x)',status:'Needs Work'}]),
      d('Leadership','Leadership',8,16,50.0,8,16,'42m 40s',1.14,LDR,'20 Mar 2026, 02:45 PM','Assesses team management, decision-making, and ability to inspire others.','AVERAGE',
        'Needs help with decision-making frameworks and understanding how to lead from the front.',
        ['Team awareness','Empathy'],
        ['Decision frameworks','Conflict handling','Inspiration'],
        {title:'Making Choices',steps:['Study the simple 4-quadrant decision matrix (urgent/important).','Practice choosing between two paths under time limits.']},
        {title:'Conflict Basics',steps:['Learn to avoid/defuse simple peer conflicts.','Study basic active listening for leaders.']},
        {title:'Confidence Building',steps:['Take on small leadership tasks (e.g. organizing a meeting).']},
        [{skill:'Leading Teams',accuracy:51,time:'Slow (1.2x)',status:'Needs Work'},{skill:'Choosing Paths',accuracy:49,time:'Slow (1.1x)',status:'Needs Work'}]),
      d('Digital Business','Digital Business',18,37,48.6,18,37,'99m 13s',1.13,DIG,'20 Mar 2026, 04:00 PM','Evaluates knowledge of digital trends, e-commerce, and technology integration in business.','WEAK',
        'Very high gap in digital business knowledge. Requires a foundational deep dive into modern enterprise tech.',
        ['Basic app usage','General internet awareness'],
        ['E-commerce operations','Digital marketing data','Emerging trends'],
        {title:'Digital Foundation',steps:['Complete a beginner\'s course on digital commerce.','Learn common digital terms (SaaS, SEO, ROI).']},
        {title:'Data Literacy',steps:['Learn to read simple bar and pie charts accurately.','Practice sorting data in spreadsheets for insights.']},
        {title:'Tech Ecosystem',steps:['Identify top 5 tech companies and their core business models.']},
        [{skill:'Tech Knowledge',accuracy:49,time:'Slow (1.2x)',status:'Needs Work'},{skill:'Digital Vision',accuracy:48,time:'Slow (1.1x)',status:'Needs Work'}]),
    ],
    psychometric:[{trait:'Openness',score:55,percentile:52,status:'PASS'},{trait:'Conscientiousness',score:50,percentile:48,status:'PASS'},{trait:'Extraversion',score:60,percentile:62,status:'PASS'},{trait:'Agreeableness',score:70,percentile:72,status:'PASS'},{trait:'Neuroticism (Low)',score:45,percentile:42,status:'PASS'}],
    summary: 'Thiganth requires immediate intervention, scoring 49.6% overall and falling into the RED band. His time efficiency is low at 160s per question. His strongest domain is Cognitive Intelligence (52.4% accuracy), but he struggles significantly with Problem Solving (47.4%) and Digital Business (48.6%). He needs to revisit foundational concepts, particularly in Pattern Recognition, Competitive Analysis & Business Models, and Storytelling with Data, as errors in these easy questions indicate critical knowledge gaps.',
  },

  // ── STU005 Rajakumaran · MBA · AMBER ─────────────────────────────────────
  STU005: {
    overall: { score:65.4, maxScore:100, percentage:65.4, band:'GOOD', totalQuestions:127, correctAnswers:83, accuracy:65.4, timeTaken:'306m 55s', timeEfficiency:'1.02x avg', needsAttention:44, estTotalTime:'315m 00s' },
    domains: [
      d('Cognitive Intelligence','Cognitive',15,21,71.4,15,21,'49m 0s',1.00,COG,'20 Mar 2026, 09:00 AM','Assesses logical reasoning, analytical thinking, and problem-solving speed.','STRONG',
        'Strong logical foundations. Rajakumaran is accurate but can be faster on simple arithmetic sets.',
        ['Logical deduction','Steady accuracy','Pattern focus'],
        ['Numerical speed','Abstract reasoning agility'],
        {title:'Numerical Pacing',steps:['Focus on Pattern Recognition speed drills.','Practice 30 mental math problems every morning.']},
        {title:'Logic Agility',steps:['Timed abstract reasoning matrices.','Solve 5 logical syllogisms per day under 4 minutes total.']},
        {title:'Consolidate Speed',steps:['Focus on reducing "think time" between questions.']},
        [{skill:'Logical Thinking',accuracy:74,time:'Avg (1.0x)',status:'Strong'},{skill:'Quantitative Pace',accuracy:68,time:'Slow (1.1x)',status:'Strong'}]),
      d('Business Intelligence','Business',13,20,65.0,13,20,'49m 20s',1.04,BIZ,'20 Mar 2026, 10:15 AM','Evaluates understanding of business concepts, market dynamics, and strategic thinking.','AVERAGE',
        'Reasonable awareness of business concepts. Needs more depth in financial analysis and industrial strategic mapping.',
        ['Market understanding','Strategy basics'],
        ['Financial Statement Interpretation','Industry analysis depth'],
        {title:'Financials Deep Dive',steps:['Focus on Financial Statement Interpretation.','Learn key ratios: Current Ratio, ROE, Debt-to-Equity.']},
        {title:'Industry Mapping',steps:['Study competitive landscape for the automobile and SaaS industries.','Practice Porter\'s 5 Forces for 3 hypothetical firms.']},
        {title:'Economic Links',steps:['Analyze how interest rate changes affect business borrowing strategy.']},
        [{skill:'Strategic Knowledge',accuracy:67,time:'Avg (1.1x)',status:'Average'},{skill:'Business Metrics',accuracy:63,time:'Slow (1.1x)',status:'Average'}]),
      d('Problem Solving','Problem Solving',12,19,63.2,12,19,'46m 12s',1.03,PRB,'20 Mar 2026, 11:30 AM','Measures ability to identify issues, analyze root causes, and develop effective solutions.','AVERAGE',
        'Can handle structured cases, but struggles when data points are conflicting or ambiguous.',
        ['Structured approach','Detail oriented','Solution paths'],
        ['Ambiguity handling','Conflicting goals optimization','Deep RCA'],
        {title:'Handling Ambiguity',steps:['Engage with case studies containing partial/conflicting data.','Practice justifying decisions with incomplete datasets.']},
        {title:'Deeper Diagnosis',steps:['Master the Ishikawa (Fishbone) diagram for complex issues.','Study cross-impact analysis.']},
        {title:'Trade-off Modeling',steps:['Model solutions that satisfy conflicting stakeholder needs.']},
        [{skill:'Issue Diagnosis',accuracy:65,time:'Avg (1.1x)',status:'Average'},{skill:'Logical Paths',accuracy:61,time:'Slow (1.1x)',status:'Average'}]),
      d('Communication','Communication',9,14,64.3,9,14,'35m 0s',1.07,COM,'20 Mar 2026, 01:00 PM','Tests verbal and written communication skills, clarity, and articulation.','AVERAGE',
        'Communication is generally clear, but professionalism and precision in writing can be enhanced.',
        ['Basic clarity','Helpful tone'],
        ['Professional Writing & Email','Message precision','Persuasion'],
        {title:'Refined Writing',steps:['Focus on Professional Writing & Email precision.','Practice drafting short, punchy progress reports.']},
        {title:'Communicating Value',steps:['Practice explaining "the why" behind a proposal.','Learn the pyramid principle for structured messaging.']},
        {title:'Feedback Skills',steps:['Practice giving and receiving critique professionally.']},
        [{skill:'Expression Clarity',accuracy:66,time:'Avg (1.1x)',status:'Average'},{skill:'Verbal Confidence',accuracy:62,time:'Slow (1.1x)',status:'Average'}]),
      d('Leadership','Leadership',11,16,68.8,11,16,'37m 48s',1.00,LDR,'20 Mar 2026, 02:45 PM','Assesses team management, decision-making, and ability to inspire others.','AVERAGE',
        'Potential leader who values consensus. Needs more confidence in leading during time-pressured crises.',
        ['Consensus building','Empathy','Reliability'],
        ['Crisis leadership','Quick decision-making','Authoritative guidance'],
        {title:'Crisis Practice',steps:['Lead time-pressured mock activities.','Focus on clarity of command in short projects.']},
        {title:'Actionable Feedback',steps:['Review frameworks for performance management conversations.','Practice setting measurable team output targets.']},
        {title:'Delegation Strategy',steps:['Study situational leadership models.']},
        [{skill:'Team Harmony',accuracy:72,time:'Avg (1.0x)',status:'Strong'},{skill:'Lead Confidence',accuracy:65,time:'Slow (1.1x)',status:'Average'}]),
      d('Digital Business','Digital Business',23,37,62.2,23,37,'89m 12s',0.97,DIG,'20 Mar 2026, 04:00 PM','Evaluates knowledge of digital trends, e-commerce, and technology integration in business.','AVERAGE',
        'Good grasp of digital tools. Needs more specialization in analytics and platform strategies.',
        ['Digital tool usage','Trend awareness'],
        ['Platform economics','Growth analytics','Tech stacking'],
        {title:'Analytics Path',steps:['Complete module on digital marketing analytics.','Practice interpreting ROAS and Conversion Funnels.']},
        {title:'Platform Strategies',steps:['Study network effects and two-sided market models.','Analyze successes of platform firms like Airbnb/Uber.']},
        {title:'Growth Hacking',steps:['Review digital growth experimentation frameworks.']},
        [{skill:'Digital Acumen',accuracy:64,time:'Avg (1.0x)',status:'Average'},{skill:'Tech Vision',accuracy:60,time:'Fast (0.9x)',status:'Average'}]),
    ],
    psychometric:[{trait:'Openness',score:88,percentile:91,status:'PASS'},{trait:'Conscientiousness',score:65,percentile:68,status:'PASS'},{trait:'Extraversion',score:95,percentile:97,status:'PASS'},{trait:'Agreeableness',score:85,percentile:87,status:'PASS'},{trait:'Neuroticism (Low)',score:70,percentile:72,status:'PASS'}],
    summary: 'Rajakumaran shows a balanced performance with an overall accuracy of 65.4% (AMBER band) and an average time of 145s per question. His strongest area is Cognitive Intelligence (71.4% accuracy), while Digital Business (62.2%) is his weakest. To improve, he should focus on minimizing unforced errors in foundational topics, specifically Pattern Recognition, Financial Statement Interpretation, and Professional Writing & Email.',
  },
};

export default STUDENT_DATA;
